[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.12.0
framework = espidf
board = esp32dev
monitor_speed = 115200
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
lib_deps =
  https://github.com/someweisguy/esp_dmx.git#9b6a5043add89038388d93ebe77109eb3368bb51
build_flags =
  -DSTAGECORE_FW_VERSION=\"0.2.0-dev.1\"
  -DSTAGECORE_DMX_TX_GPIO=17
  -DSTAGECORE_DMX_RTS_GPIO=21
  -DSTAGECORE_DMX_UNIVERSE_SIZE=12
